<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <title>Email Notification System</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <style type="text/css">

        body {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            color: #565656;
        }

        .text {
            margin-top: 0;

            font-size: 14px;
            line-height: 25px;
            margin-bottom: 25px
        }

        .logo {
            border: 0;
            -ms-interpolation-mode: bicubic;
            display: block;

            width: 250px;
            height: auto;
            margin-left: 70px;

        }

        .footer {

            font-size: 11px;
            margin-bottom: 1px;
            margin-top: 1px;
        }

        hr.e {
            border: 0;
            height: 1px;
            background: #333;
            background-image: linear-gradient(to right, #ccc, #333, #ccc);
        }

    </style>

</head>
<body>
<div class="container">

    <div id="emb-email-header">
        <img class="logo" src="http://www.lestroismarios.com/images/3marios_logo_v7.png" alt="L3M Logo">
    </div>

    <p class="text">A new comment has been posted, please visit <a
            href="http://www.lestroismarios.com/php/customer.php">lestroismarios.com</a> to review it.</p>
    <hr class="e">
    <p class="text">
        <b>Contract: </b> Lowney Phase 8
        <br>
        <b>From: </b>Mario Alejandro Blanco
        <br>
        <b>Subject: </b> Servicio Limpieza
        <br>

    <p class="text" style="margin-left: 20px;">

        Distribudor del bano de las mujeres cambiado por salidero, ver fotos antes y despues<br/>

        Cambiar bombillos mr16 sauna húmeda en el techo<br/>

        Sofa del rc phase 8 con manchas blancas en el cogin, ver foto y reportar<br/>

        Aspirar terraza phase 8<br/>

        Bombillo moscas phase 8 reciclage<br/>

        Aspirar terraza phase 9<br/>

        Pasarle a las sillas de la terraza phase 9 en el chalet urbain a diario<br/>

    </p>
    <a href="photos/12/desert.jpg"> <img src="photos/12/desert.jpg" class="img-thumbnail" alt="Lowney" width="300"
                                         height="350"></a>
    <a href="photos/12/desert.jpg"> <img src="photos/12/flower.jpeg" class="img-thumbnail" alt="Lowney" width="300"
                                         height="350"></a>
    <a href="photos/12/desert.jpg"> <img src="photos/12/sunset.jpg" class="img-thumbnail" alt="Lowney" width="300"
                                         height="350"></a>
    <a href="photos/12/desert.jpg"> <img src="photos/12/water.jpg" class="img-thumbnail" alt="Lowney" width="300"
                                         height="350"></a>
    <a href="photos/12/desert.jpg"> <img src="photos/12/desert.jpg" class="img-thumbnail" alt="Lowney" width="300"
                                         height="350"></a>
    <a href="photos/12/desert.jpg"> <img src="photos/12/desert.jpg" class="img-thumbnail" alt="Lowney" width="300"
                                         height="350"></a>

    </p>


    <hr class="e">
    <p class="footer">You received this notification because you are registered as a user in lestroismarios.com.
        To stop receiving these notification visit MY ACCOUNT and uncheck notify me by email of new comment posted.</p>

    <p class="footer">Please do not reply to this email which have been generated by our system. If you have questions
        regarding
        this email please do not hesitate to contact us to the information provided in our website under the section
        CONTACT.</p>
    <hr class="e">

</div>

</body>
</html>







